import os
import sys
import subprocess
import bulkPlasmidSeq

from Bio import SeqIO
from Bio.Emboss.Applications import NeedleCommandline

def run(reads, reference, outputDir, args):
    '''
    Takes as input fastq reads or directory to reads,
    a fasta file with all the plasmid or directory pointing to the plasmid files. 
    '''
        
    if None not in (reads, reference, outputDir):
        
        runMedaka(reads, reference, outputDir, args.threads, args.model, args.screenshot, args.igv)
            
        
    else:
        sys.exit('Medaka needs input reads (-i), output directory (-o), and reference sequences (-r)')



def runMedaka(reads, reference, outputDir, threads, model, screenshot, igv):
    '''
    Takes the input reads, reference, and output directory (after being processed through loadReads) and runs Medaka.
    Please see Dependencies.txt or https://github.com/nanoporetech/medaka for more information about installing medaka.
    Only medaka_consensus used in this pipeline.
    '''
    print('----------------------------------\n')
    print('Running Medaka with the following arguments, more info in medaka_log.txt')
    print('----------------------------------\n')
    print('Input files: %s \nReference Files: %s \nOutput directory: %s \nThreads: %s \nModel: %s\n'
         % (reads, reference, outputDir, str(threads), model))
    
    if os.path.isfile(outputDir):
        sys.exit('Ouput directory exists')
    
    elif not os.path.exists(outputDir):
        subprocess.run(['mkdir %s' % outputDir], shell = True)
    
    with open('%s/medaka_log.txt' % outputDir, 'wt') as log:
        # Quietly run medaka, make a medaka_log
        #20210512 Added back -g (no fill option, want to see least helped results)
        subprocess.run(['medaka_consensus', '-g', '-i', str(reads), '-d', str(reference),
                        '-o', str(outputDir), '-t', str(threads), '-m', str(model)],
                       stdout = log, stderr = log, check = True)
    
    processMedakaOutput(outputDir, reference, screenshot, igv)
    
    return 


def processMedakaOutput(outputDir, reference, screenshot, igv = None):
    '''
    Splits the consensus.fasta file that was generated by Medaka into individual plasmid seqs. Use referen
    '''
    if os.path.isdir(outputDir):
        consensusFile = outputDir+'/consensus.fasta'
        needle_commands = []
        subprocess.run(['mkdir', '%s/consensus_sequences' % outputDir])
        destination = outputDir+'/consensus_sequences/'
        
        for record_reference in SeqIO.parse(consensusFile, 'fasta'):
            for record_consensus in SeqIO.parse(reference, 'fasta'):
                if record_con.name == record_ref.name: #Match the consensus to the reference
                    SeqIO.write(record_consensus, destination + record_consensus.name+'_consensus.fasta', 'fasta')
                    SeqIO.write(record_reference, outputDir + record_reference.name+'_reference.fasta', 'fasta')
                    needle_commands.append(NeedleCommandline(asequence = outputDir + record_reference.name+'_reference.fasta',
                                                         bsequence = destination + record_consensus.name+'_consensus.fasta',
                                                         gapopen = 10,
                                                         gapextend = 0.5,
                                                         outfile = destination + record_consensus.name + '.txt'))
            
    for command in needle_commands:
        subprocess.run(str(command), shell = True)
                
    #Run take screenshots based on final_processed.bam    
    if screenshot:
        bulkPlasmidSeq.takeScreenshots(reference, outputDir, igv)
        
def produce_alignments(output_dir);

    return